# Generated by Django 4.0.4 on 2022-05-29 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('familiares', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='familiares',
            name='cumple',
            field=models.CharField(max_length=40, null=True),
        ),
    ]
