# Generated by Django 4.0.4 on 2022-05-29 22:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('familiares', '0003_rename_cumple_familiares_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='familiares',
            name='date',
        ),
    ]
