# Generated by Django 4.0.4 on 2022-05-29 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('familiares', '0004_remove_familiares_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='familiares',
            name='fecha',
            field=models.CharField(max_length=40, null=True),
        ),
    ]
