# Generated by Django 4.0.4 on 2022-05-29 22:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('familiares', '0005_familiares_fecha'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='familiares',
            name='fecha',
        ),
    ]
