# Generated by Django 4.0.4 on 2022-05-30 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('familiares', '0006_remove_familiares_fecha'),
    ]

    operations = [
        migrations.AddField(
            model_name='familiares',
            name='fecha',
            field=models.CharField(default=0.0005042864346949068, max_length=40),
            preserve_default=False,
        ),
    ]
